### PR TITLE
Fix DepthPlanar capture

### LINKED ISSUE #3648: "DepthPlanar" type image pulbished by ros airsim_node is actually not a depth image
## Bug report 

- AirSim Version/#commit: 1.4.0
- UE/Unity version: 4.25.4
- autopilot version: 
- OS Version: ubuntu 18.04 LTS

### What's the issue you encountered?

I am trying to use airsim with ros, and want to use depth image published from the camera attached to the vehicle.
Until previous version ( AirSim 1.3.1 with Unreal 4.24.4), there was no problem using "ImageType 1"(DepthPlanner). The airsim_node published proper depth image. However, after updating my Unreal / AirSim version to the latest version, "DepthPlanar" message from the airsim_node changed to grayscale image of the RGB image, not the depth image. 
Using ImageType = 2(DepthPerspective) does not produce this type of error.

image
The screenshot above is a snapshot of a simualtion.

image
DetphPlanar image visualized by rviz. This is clearly not a depth image.

### Settings

Here is my settings.json. This version of the document is based on computer vision mode, but same problem occurs when using other vehicle types.
```
{
  "SettingsVersion": 1.2,
  "SimMode": "ComputerVision",
  "ClockType": "",
  "ClockSpeed": 1,
  "LocalHostIp": "127.0.0.1",
  "RecordUIVisible": true,
  "LogMessagesVisible": true,
  "ViewMode": "Fpv",
  "SpeedUnitFactor": 1.0,
  "SpeedUnitLabel": "m/s",

  "CameraDefaults": {
    "CaptureSettings": [
      {
        "ImageType": 0,
        "Width": 256,
        "Height": 144,
        "FOV_Degrees": 90,
        "AutoExposureSpeed": 100,
        "AutoExposureBias": 0,
        "AutoExposureMaxBrightness": 0.64,
        "AutoExposureMinBrightness": 0.03,
        "MotionBlurAmount": 0,
        "TargetGamma": 1.0,
        "ProjectionMode": "",
        "OrthoWidth": 5.12
      }
    ]
  },
  "OriginGeopoint": {
    "Latitude": 47.641468,
    "Longitude": -122.140165,
    "Altitude": 122
  },
  "TimeOfDay": {
    "Enabled": false,
    "StartDateTime": "",
    "CelestialClockSpeed": 1,
    "StartDateTimeDst": false,
    "UpdateIntervalSecs": 60
  },
  "SegmentationSettings": {
    "InitMethod": "",
    "MeshNamingMethod": "",
    "OverrideExisting": false
  },
  "PawnPaths": {
    "BareboneCar": {"PawnBP": "Class'/AirSim/VehicleAdv/Vehicle/VehicleAdvPawn.VehicleAdvPawn_C'"},
    "DefaultCar": {"PawnBP": "Class'/AirSim/VehicleAdv/SUV/SuvCarPawn.SuvCarPawn_C'"},
    "DefaultQuadrotor": {"PawnBP": "Class'/AirSim/Blueprints/BP_FlyingPawn.BP_FlyingPawn_C'"},
    "DefaultComputerVision": {"PawnBP": "Class'/AirSim/Blueprints/BP_ComputerVisionPawn.BP_ComputerVisionPawn_C'"}
  },
  "Vehicles": {
    "ComputerVision": {
      "VehicleType": "ComputerVision",
      "AutoCreate": true,
      "PawnPath": "",
      "EnableCollisionPassthrogh": false,
      "EnableCollisions": true,
      "AllowAPIAlways": true,
      "Cameras": {
                "front_center_custom": {
                  "CaptureSettings": [
                    {
                      "PublishToRos": 1,
                      "ImageType": 0,
                      "Width": 640,
                      "Height": 480,
                      "FOV_Degrees": 90.0                    
                    },
		                {
                      "PublishToRos": 1,
                      "ImageType": 1,
                      "Width": 640,
                      "Height": 480,
                      "FOV_Degrees": 90.0,
                      "DepthOfFieldFstop": 500.0,
                      "DepthOfFieldFocalDistance": 20.0, 
                      "DepthOfFieldFocalRegion": 20.0
                    }
                  ],
		  "NoiseSettings": [
      		{
        	"Enabled": true,
        	"ImageType": 0,

        	"RandContrib": 0.1,
        	"RandSpeed": 100000.0,
        	"RandSize": 500.0,
        	"RandDensity": 2,

        	"HorzWaveContrib":0.003,
        	"HorzWaveStrength": 0.008,
        	"HorzWaveVertSize": 1.0,
        	"HorzWaveScreenSize": 1.0,

        	"HorzNoiseLinesContrib": 0.1,
        	"HorzNoiseLinesDensityY": 0.01,
        	"HorzNoiseLinesDensityXY": 0.5,

        	"HorzDistortionContrib": 0.1,
        	"HorzDistortionStrength": 0.002
      		}
    		],
                  "X": 0.00, "Y": 0.0, "Z": .0.00,
                  "Pitch": 0, "Roll": 0, "Yaw": 0
                }
            },
      "X": 0.00, "Y": 0.00, "Z": 0.0,
      "Pitch": 0.0, "Roll": 0.0, "Yaw": 0.0
    }
  },
  "SubWindows": [
    {"WindowID": 0, "ImageType": 0, "CameraName": "front_center_custom", "Visible": true},
    {"WindowID": 1, "ImageType": 1, "CameraName": "front_center_custom", "Visible": true}
  ]
}

```

### How can the issue be reproduced?

Play airsim with the settings.json file above, and launch airsim_node.launch.

### Include full error message in text form

(Does not include error message)

**What's better than filing an issue? Filing a pull request :).**

### LINKED ISSUE #3716: I try to use ImageType.Depthplanar output depth image, but it outputs a gray scale image. Not depth image.
## Bug report 

- AirSim Version/#commit:
- UE/Unity version:
- autopilot version:
- OS Version:

### What's the issue you encountered?

I try to use ImageType.Depthplanar output depth image, but it outputs a gray scale image. Not depth image. 
### How can the issue be reproduced?

1.
2.

### Include full error message in text form

**What's better than filing an issue? Filing a pull request :).**

### LINKED ISSUE #3776: DepthPerspective is binary, DepthPlanar is grayscale.
### Using AirSimNH to collect scene, depth, segmentation in a mono camera setting. 
I tried using the hello_car.py, cv_mode.py examples, and those also had similar output. 

  

I am sorry if this question is repetitive, I am just few days old in learning AirSim. So can anyone provide the steps clearly on my mistake.

I am using Windows 10, Unreal 4.25.4 

This is my settings.json, PixelsAsFloat is set  to true here.
```
{
  "SettingsVersion": 1.2,
  "SimMode": "Car",
  "SpeedUnitFactor": 1,
  "Recording": {
    "RecordOnMove": false,
    "RecordInterval": 0.05,
    "Cameras": [
      {
        "CameraName": "0",
        "ImageType": 0,
        "PixelsAsFloat": false,
        "Compress": true
      },
      {
        "CameraName": "0",
        "ImageType": 2,
        "PixelsAsFloat": true,
        "Compress": true
      },
      {
        "CameraName": "0",
        "ImageType": 5,
        "PixelsAsFloat": true,
        "Compress": true
      }
    ]
  },

  "CameraDefaults": {
    "CaptureSettings": [
      {
        "ImageType": 0,
        "Width": 640,
        "Height": 480,
        "FOV_Degrees": 90,
        "TargetGamma": 2.0
      },
      {
        "ImageType": 2,
        "Width": 640,
        "Height": 480,
        "FOV_Degrees": 90
      },
      {
        "ImageType": 5,
        "Width": 640,
        "Height": 480,
        "FOV_Degrees": 90
      }
    ]
  }
}
```

When I use "DepthPlanar"  by choosing the ImageType: 1, the output looks like grayscale. (Uses blocks environment)

DepthPlanar

When I use "DepthPerspective"  by choosing the ImageType: 2, the output looks binary. I checked issues #921 but I am not using python scripts to obtain data, but directly playing the GUI and record 
depthPerspective

I suspect I am making a mistake in the settings.json file that  is causing this issue, can I get some help for this ?

### PR DESCRIPTION
**Pull request by saihv**
Fixes: https://github.com/microsoft/AirSim/issues/3776
Fixes: https://github.com/microsoft/AirSim/issues/3716
Fixes: https://github.com/microsoft/AirSim/issues/3648

### About
Fixes an issue with PIPCamera where it was missing the reference to the Depth Planar material. Earlier, requesting a DepthPlanar issue would return a grayscale/RGB image instead of depth.

### How Has This Been Tested?

```
import airsim
import cv2
import numpy as np

c = airsim.MultirotorClient()

c.confirmConnection()

responses = c.simGetImages([airsim.ImageRequest("1", airsim.ImageType.DepthPlanar, True)])
response = responses[0]
img1d = response.image_data_float
img2d = np.reshape(img1d,(response.height, response.width)) 
cv2.imshow("Depth viz", img2d)
cv2.waitKey(0)
```

### CODE REVIEW

**Review by zimmy87 — CHANGES_REQUESTED** [review]
Hi @saihv, which version of the unreal engine are you using to save the .uasset in this PR? In UE 4.25.4, I'm getting load failures when launching the Blocks environment:

---------------------------
Message
---------------------------
Default Property warnings and errors:
Error: CDO Constructor (CarPawn): Failed to find /AirSim/Blueprints/BP_PIPCamera.BP_PIPCamera_C

Error: CDO Constructor (ComputerVisionPawn): Failed to find /AirSim/Blueprints/BP_PIPCamera.BP_PIPCamera_C

Error: CDO Constructor (SimModeBase): Failed to find /AirSim/Blueprints/BP_PIPCamera.BP_PIPCamera_C

Error: CDO Constructor (SimModeBase): Failed to find /AirSim/Blueprints/BP_PIPCamera.BP_PIPCamera_C

The BP_PIPCamera.uasset file doesn't appear in the content browser, and launching the environment results in an unhandled exception and crash. Would you be able to re-save your changes in UE 4.25 to ensure compatibility with the currently supported version of Unreal?

**Comment by rajat2004** [comment]
I can't see the output but shouldn't this 4.25 incompatibility have been caught by the Azure Pipelines? It uses 4.25.1 based on the ci.yaml file

**Comment by saihv** [comment]
@zimmy87 I've replaced the asset with a 4.25-saved one, could you try now?

**Comment by madratman** [comment]
@saihv seems like you pushed `Unreal/Environments/Blocks/Content/FlyingCPP/Maps/FlyingExampleMap.umap` by mistake instead of `/Unreal/Plugins/AirSim/Content/Blueprints/BP_PIPCamera.uasset` by mistake

**Comment by saihv** [comment]
Whoops, fixed!

**Comment by zimmy87** [comment]
Thanks for the submission @saihv! Tested locally and it works for me.

**Review by zimmy87 — APPROVED** [review]

**Pull request merged**
