### PR TITLE
[Mavlinkcom/UdpSocket] Fix select() compilation error on OSX

### PR DESCRIPTION
**Pull request by rajat2004**
Error reported here - https://github.com/microsoft/AirSim/issues/2559
Not sure if this is the correct fix though, needs testing

@saihv You have a OSX machine right? If possible, could you test this? Not sure why this hasn't come up till now

### CODE REVIEW

**Comment by saihv** [comment]
Interesting - will give it a shot today, but it looks like the error is about an overflow setting on a file descriptor (socket)? Is that related to `select`?

**Comment by rajat2004** [comment]
That's what I'm not sure about. `select` seems to be the most probable one, but from the OSX man pages, seems correct. It's a compile-time error which seems pretty strange that it hasn't popped up till now
Can't do much more investigtion without some more info

BTW, is there any easy way to test out OSX on a non-Mac machine? Maybe VirtualBox?

**Comment by saihv** [comment]
So this does build fine, but I am not sure how to test it properly w.r.t. the issue - because master works without issues as well..

> BTW, is there any easy way to test out OSX on a non-Mac machine? Maybe VirtualBox?

The feasibility exists, because macOS runs on Intel processors; but [Apple's EULA states that running the OS on non-Mac computers is illegal](https://images.apple.com/legal/sla/docs/macOS1012.pdf)

**Comment by rajat2004** [comment]
Great, thanks for testing! So I think that if the error can't be reproduced and is found to be the result of some faulty configuration, then this can be closed

**Comment by rajat2004** [comment]
Closing this till the error gets reproduced, can be reopened then. This anyways doesn't seem to be the correct fix

**Pull request closed without merging**
