### PR TITLE
libc++ / libstdc++ compatibility issues

### PR DESCRIPTION
**Pull request by mescarra**
Fix related to this issue:
https://github.com/Microsoft/AirSim/issues/893

### CODE REVIEW

**Comment by sytelus** [comment]
Are you really sure removing std:: is the right approach. This should be supported by any compliant C++11 compiler. Also, I'm not sure about removing c++abi. Removing ABI can generate hidden hard to catch issues. Are there any other alternatives?

**Comment by aburgm** [comment]
In C++ you can just use `std::abs` instead of fabsf if you include `<cmath>`. `std::abs` is overloaded for that purpose. See http://en.cppreference.com/w/cpp/numeric/math/fabs

**Comment by mescarra** [comment]
Yes, using the overloaded `std::abs` is the right approach, I should modify that.

About the llvm's `libc++abi`, I believe clang's compiled programs are still being compiled against `c++abi` due to the `CommonSetup` inclusion.

On the other hand, I'm quite sure `libstdc++` does not separate the ABI in a different library, so it wouldn't be necessary when compiling with gcc defaults.

**Comment by sytelus** [comment]
Sounds good. Thanks for looking into this.

**Comment by sytelus** [comment]
I made above changes and have merged this.

**Pull request merged**
