### PR TITLE
Extend default recording of images/poses to all vehicles in a scene

### PR DESCRIPTION
**Pull request by saihv**
The currently default recording code (record button in-game, or key R) only records images and position/orientation data for the first vehicle in the game. This PR extends that functionality to all vehicles, by dealing with the full list of vehicle APIs (`VehicleSimApiBase` objects) rather than just one. For `n` vehicles in a scene, recording `n` images and `n` poses in `airsim_rec.txt` is treated as one step.

Note: This has only been tested on drones for up to five vehicles.

### CODE REVIEW

**Comment by sytelus** [comment]
Thanks. This is good change but extensive as well. I'll go through this early next week.

**Comment by saihv** [comment]
Just a quick note from my testing: it looks like having multiple vehicles recording simultaneously is causing AirSim to be more prone to the Game <-> Recording thread deadlock issue mentioned in https://github.com/Microsoft/AirSim/issues/1694. Utilizing the fix provided in the related PR: https://github.com/Microsoft/AirSim/pull/1695 seems to fix the problem for the multi vehicle recording case as well.

FYI, if it's helpful in any way: extending the recording to multiple vehicles does not cause the deadlock problem in v1.2.0 (Windows), only in the latest versions.

**Comment by zhuboshun2015** [comment]
@saihv Could you give more details about how to achieve this ? I have modified the code(Extend default recording of images/poses to all vehicles) as you  upload,

 but next step is ?

**Comment by zhuboshun2015** [comment]
> 谢谢。这是一个很好的改变，但也很广泛。下周初我会经历这个。

Hello ! Did you achieve that?

**Comment by saihv** [comment]
@zhuboshun2015 If you've already adapted these changes into your code, all you'd have to do is press 'R' as you usually would, and images/poses from all drones will be recorded.

**Comment by zhuboshun2015** [comment]
@saihv Yes, I did.But when I look at the.txt file, it seems that there is only the position and posture information of drone1.I don't know if I have to set 'settings.json'? This is my settings.json document.
[settings.txt](https://github.com/Microsoft/AirSim/files/3145059/settings.txt)

**Comment by zhuboshun2015** [comment]
@saihv  thank you ! I have success in doing this . But it is a little difficult to recognize every drone's number.How do you recognize this ?

**Pull request closed without merging**
