### PR TITLE
Unity: Placeholder functions for compilation

### PR DESCRIPTION
**Pull request by rajat2004**
Fixes compilation errors, tested to be working on Linux (Unity 2019.f2) after combining with https://github.com/microsoft/AirSim/pull/2328

### CODE REVIEW

**Comment by saihv** [comment]
Thanks for this! I just realized I missed retargeting the Unity wrapper vcxproj. I'll do that and test this on Windows

**Comment by saihv** [comment]
@rajat2004 I was able to build the Unity plugin successfully on Windows, but when I click on play with SimModeSelector, the engine crashes with no useful info. Do I need to absorb https://github.com/microsoft/AirSim/pull/2328 as well to test successfully?

**Comment by rajat2004** [comment]
@saihv I don't think so, none of the changes in https://github.com/microsoft/AirSim/pull/2328 should actually impact Windows
Any missing functions, errors in the console? Maybe check one of the Log files - https://docs.unity3d.com/Manual/LogFiles.html

**Comment by saihv** [comment]
My bad, it was actually just a problem with my `settings.json` - so can confirm, it's working on Windows.

**Comment by rajat2004** [comment]
Great, glad to know it's working!

**Pull request merged**
