### PR TITLE
Update README Document.

### PR DESCRIPTION
**Pull request by Varun-Strangelet**

### CODE REVIEW

**Review by rajat2004 — CHANGES_REQUESTED** [review]
Is there a reason for this, the current Readme is fine and the proposed changes just make it bad.
Or was it meant to be something else?

**Comment by Varun-Strangelet** [comment]
ohk I am Sorry I Am new to Gtihub and I was practice of sent pull request
to anyone..

**Comment by rajat2004** [comment]
Okay, then if you do want to propose some changes, then add new commits. Otherwise, I think this PR can be closed.
Welcome to the world of open-source!

**Comment by Varun-Strangelet** [comment]
Ohk Thanks

**Pull request closed without merging**
