### PR TITLE
Add simDisableCamera API

### LINKED ISSUE #1766: Calling simGetImage or simGetImages once drops performance permanently. Why?
Calling simGetImage or simGetImages from python or C++ permanently impacts rendering framerate. In my case I am running at 60fps generally and can communicate with unreal via other airsim lightweight APIs without framerate costs.

As soon as simGetImage or simGetImages is called, the framerate drops to 20fps on my machine. Even if I call simGetImage once, the framerate is reduced. Can you explain where in the code the permanent cost is paid? You must be scheduling simGetImage tasks continuously in Unreal as RenderTasks, are you? Why does the performance drop permanently?

The recording button ( because it calls the same api ) will also drop performance at the same rate.

I understand that you optimized the performance ( ReadSurfaceData and not ReadPixels ) to bring it up to the current level, as you mention here:
https://stackoverflow.com/questions/43218678/unreal-engine-accessing-saving-in-game-images-to-disk-without-blocking-game-thr/43287505

Also interesting to mention that the actual performance drop is the same whether you are capturing several camera views or just one, which makes me feel that the cost is paid out of render thread management.

### LINKED ISSUE #2464: Add function to disable a camera via API
Currently all configured cameras become active as soon as they are used.
They will stay active even if they are not used and degrade the performance unnecessary.

In interactive mode they can be toggled on and off via key - this is not the case in headless mode or if the API is used.

There should be a function to deactivate a camera (and maybe to activate - or it activates automatically when an image is requested).

Related: https://github.com/microsoft/AirSim/issues/2389

### PR DESCRIPTION
**Pull request by rajat2004**
Closes https://github.com/microsoft/AirSim/issues/2464, https://github.com/microsoft/AirSim/issues/2389

Without `simDisableCamera`-
```
$ python3 test_camera.py
Connected!
Client Ver:1 (Min Req: 1), Server Ver:1 (Min Req: 1)

Time spent for 30 frames: 0:00:01.008567
Time spent for 30 frames: 0:00:01.033204
Time spent for 30 frames: 0:00:01.029388
Time spent for 30 frames: 0:00:01.053637
Time spent for 30 frames: 0:00:01.059051
Time spent for 30 frames: 0:00:01.067620
Time spent for 30 frames: 0:00:01.054935
Time spent for 30 frames: 0:00:01.060000
Time spent for 30 frames: 0:00:01.040280
Time spent for 30 frames: 0:00:01.101260
Time spent for 30 frames: 0:00:01.060938
Time spent for 30 frames: 0:00:01.108110
Time spent for 30 frames: 0:00:01.150538
Time spent for 30 frames: 0:00:01.093519
Time spent for 30 frames: 0:00:01.060111
Time spent for 30 frames: 0:00:01.051841
High resolution image captured.
Time spent for 30 frames: 0:00:01.925659
Time spent for 30 frames: 0:00:02.788289
Time spent for 30 frames: 0:00:02.831024
Time spent for 30 frames: 0:00:02.813883
```

With `simDisableCamera`-
```
Time spent for 30 frames: 0:00:01.092915
Time spent for 30 frames: 0:00:01.057923
Time spent for 30 frames: 0:00:01.062711
Time spent for 30 frames: 0:00:01.062194
Time spent for 30 frames: 0:00:01.138591
Time spent for 30 frames: 0:00:01.090212
Time spent for 30 frames: 0:00:01.048497
Time spent for 30 frames: 0:00:01.060650
Time spent for 30 frames: 0:00:01.096157
Time spent for 30 frames: 0:00:01.049348
Time spent for 30 frames: 0:00:01.104762
Time spent for 30 frames: 0:00:01.102033
Time spent for 30 frames: 0:00:01.055395
Time spent for 30 frames: 0:00:01.097566
Time spent for 30 frames: 0:00:01.094629
Time spent for 30 frames: 0:00:01.138703
High resolution image captured.
Time spent for 30 frames: 0:00:01.414585
Time spent for 30 frames: 0:00:01.041129
Time spent for 30 frames: 0:00:01.139397
Time spent for 30 frames: 0:00:01.067039
Time spent for 30 frames: 0:00:01.041106
Time spent for 30 frames: 0:00:01.079655
```

Only Unreal Engine for now, problem in parsing the settings in Unity
Hiding the whitespace changes makes it much easier to review (Sorry for this, editor settings)

### CODE REVIEW

**Comment by rajat2004** [comment]
Placeholder only in Unity for now since there are problems in Unity's settings parsing I think
Will also need to figure out how to implement this in Unity, more convoluted than Unreal currently

**Comment by madratman** [comment]
Hmm, I think it would be ideal to handle this on C++ side itself, instead of asking the user to call a `simDisableCamera`?
Perhaps we can incorporate this in https://github.com/microsoft/AirSim/pull/2472 or after #2472 is in? 
cc @ironclownfish

**Comment by rajat2004** [comment]
Yes, it might be better to disable the camera right inside AirSim after `getImage` completes, but will need to test if there's any performace impact when a camera is being used continuously
Better to get this in after #2472 gets merged

**Comment by rajat2004** [comment]
I've included a one-line fix for this as mentioned by @madratman in #2713, one main problem is that PR mostly won't get merged anytime soon
Seems to be 2 other options - 

1. Open another PR to apply the one-line fix to current master, thereby not having the API
2. Rebase this PR which adds the API and requires user to use it

I prefer the 1st option, let me know which seems better

**Comment by rajat2004** [comment]
Replaced by #2881

**Pull request closed without merging**
