### PR TITLE
Distance sensor Upgrades

### LINKED ISSUE #2723: Visualizing sensors data in Client side (Unreal)
I am trying to visualise sensors data (Distance and Lidar sensors data ) in unreal engine, what the right way to approach this

### LINKED ISSUE #2806: Distance Detection Right in Front of Drone
Hello, 

So I would like to be able to detect the distance from just one point in front of the drone it see if there is anything immediately in front of it.

I know I cannot just use the distance sensor (since they can only for now detect distance from the drone to floor) But is there anyone way I can shift that to just in front of the drone. Or can I just use the Lidar to only detect 1 point in front of the drone?

### PR DESCRIPTION
**Pull request by rajat2004**
1. Add setting for drawing debug point with Distance Sensor
2. Expose Distance sensor settings, also move sensor above Car vehicle by 1 meter by default 
3. Fix `DistanceSensorData` struct in `types.py` (Should be float, not Quaternion)
4. Update docs
5. Use Custom sensor orientation in Mavlink Distance Sensor message (Needs testing with PX4)
6. ROS wrapper change
7. Example script for Distance sensor with 2 cars

Default sensor-
Screenshot from 2020-06-28 08-42-07

Downward-facing (altitude measurement)-
Screenshot from 2020-06-28 11-35-03

2 Cars with distance sensor
Screenshot from 2020-07-24 10-30-09

Closes #2723, closes #2806
Related issues - #2444, #1029

Question: Should there be fields in settings for other params such as `update_frequency`, noise, etc? Currently haven't added those

### CODE REVIEW

**Comment by mirarmdn** [comment]
How does the distance sensor airsim measure the distance from the car to the obstacles in front? because from the simulation that has been done, the result of the distance always increases even though the distance from the car to the obstacle is getting closer
anyone can help, please

**Comment by rajat2004** [comment]
@mirarmdn Distance sensor uses a ray cast to measure the distance. You're right, I just tested, and there's some problem with Car vehicle, the distance values don't make sense. It's working correctly on Multirotor vehicle though. Need to look into this

**Comment by mirarmdn** [comment]
@rajat2004 What should I do? I desperately need the distance sensors to measure the distance from the car to the obstacle. I've looked into several sources, but I haven't found an answer. Can you help me
Thank you

**Comment by rajat2004** [comment]
@mirarmdn I've pushed the fix for the Car vehicle, the problem was that the sensor was inside the vehicle, and so gave the wrong values. Moving it by 1 meter above fixes the problem, this is also being done in Lidar as well. Added an example script as well for measuring the distance between 2 vehicles which I used for testing 

Screenshot from 2020-07-24 10-30-09

**Comment by madratman** [comment]
This PR is looking good and complete to me. @rajat2004 do you want to add anything else here?

**Comment by rajat2004** [comment]
@madratman Don't think so, I was thinking of adding support for distance sensor in ArduCopter, Rover vehicles but that will take time and requires a PR in AP repository to be merged first, so this can go in and will open a new PR later when that happens.
One point s whether fields like noise, etc should be exposed in settings or not, right now haven't done that.

**Comment by madratman** [comment]
Yes, let's add those features in next PR. I'm getting this in.

**Comment by fracnaive** [comment]
Problem:
It always get the same result ZERO no matter how i change "X","Y","Z" of Distance Sensors when i run the distance_sensor_multi.py.
my settings.json:
{"SeeDocsAt": "https://github.com/Microsoft/AirSim/blob/master/docs/settings.md","SettingsVersion": 1.2,"SimMode": "Car", "Vehicles": {"Car1": {"VehicleType": "PhysXCar","AutoCreate": true, "Sensors": { "Distance": { "SensorType": 5, "Enabled" : true,"X": 0, "Y": 0, "Z": 5, "DrawDebugPoints": true}}}, "Car2": {"VehicleType": "PhysXCar", "AutoCreate": true, "X": 10, "Y": 0, "Z": 0, "Sensors": {"Distance": { "SensorType": 5, "Enabled" : true,"X": 0, "Y": 0, "Z": 5,"DrawDebugPoints": true }}}}}
result:
Connected!
Client Ver:1 (Min Req: 1), Server Ver:1 (Min Req: 1)

Distance sensor data: Car1: 0.0, Car2: 0.0
Distance sensor data: Car1: 0.0, Car2: 0.0
Distance sensor data: Car1: 0.0, Car2: 0.0
Distance sensor data: Car1: 0.0, Car2: 0.0
Distance sensor data: Car1: 0.0, Car2: 0.0
Distance sensor data: Car1: 0.0, Car2: 0.0
Distance sensor data: Car1: 0.0, Car2: 0.0
Distance sensor data: Car1: 0.0, Car2: 0.0
Distance sensor data: Car1: 0.0, Car2: 0.0
Distance sensor data: Car1: 0.0, Car2: 0.0

image

**Comment by rajat2004** [comment]
@fracnaive Your sensor is probably below the vehicle, in the ground itself. NED is used here, so +ve Z will be downwards.
Also for the future, it's preferable to create a new issue

**Comment by fracnaive** [comment]
I get it，thanks！

**Pull request merged**
