### PR TITLE
fix4475

### LINKED ISSUE #4475: camera_tf is ambiguous when diffrent vehicles have same camera names in ROS2
The camera_tf(optical, body, optical/static, body/static) header.child_frame_id has no vehicle name part.

This leads ambiguous tf2_ros::Buffer::lookupTransform betweent two camera tfs when multiple vehicles have same camera name.

Besides, it is also ambiguous  when creating camera's subframes.

Other sensors(imu,gps,lidar...) have no this issue. their tf header.child_frame_id  has vehicle name part.

### PR DESCRIPTION
**Pull request by dzywater**
fix: #4475

### CODE REVIEW

**Comment by dzywater** [comment]
Error on ubuntu18.04: 
....
 Err:1 http://azure.archive.ubuntu.com/ubuntu bionic-updates/universe amd64 vulkan-utils amd64 1.1.70+dfsg1-1ubuntu0.18.04.1
  Could not connect to azure.archive.ubuntu.com:80 (52.147.219.192), connection timed out
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/v/vulkan/vulkan-utils_1.1.70+dfsg1-1ubuntu0.18.04.1_amd64.deb  Could not connect to azure.archive.ubuntu.com:80 (52.147.219.192), connection timed out
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Error: Process completed with exit code 100.

**Comment by zimmy87** [comment]
Hey @dzywater, thank you for submitting this PR! I've tested this locally and it's working for me, so I'd like to get this merged, but there are conflicts with the latest master that need to be resolved before that can be done. Can you resolve this PR with the latest master?

**Comment by dzywater** [comment]
> Hey @dzywater, thank you for submitting this PR! I've tested this locally and it's working for me, so I'd like to get this merged, but there are conflicts with the latest master that need to be resolved before that can be done. Can you resolve this PR with the latest master?

I feel the review and merge time is a little long, I have forgot some bugs and improvements that I wanted to do.
My own ros2 package moves ahead far so that It is difficult for me to find out the differences.

**Comment by zimmy87** [comment]
Thank you for submitting this PR and resolving the conflicts with master @dzywater! The AirSimCI Ubuntu_1804 check is failing due an issue with a CUDA repository unrelated to this fix, so I am moving ahead with merging this.

**Pull request merged**
