### PR TITLE
Update xbox_controller.md

### PR DESCRIPTION
**Pull request by Mayankm96**
* Adding more description to how to use the contoller as shown in issue #[212](https://github.com/Microsoft/AirSim/issues/212)
* For HIL, you don't need a PX4 connected to the serial port which is a bit confusing as the MavLinktest step is redundant for that. The PX4 SITL works fine. 
*  The XBox360ce might need to be checked.

### CODE REVIEW

**Comment by andre-nguyen** [comment]
> For HIL, you don't need a PX4 connected to the serial port which is a bit confusing as the MavLinktest step is redundant for that. The PX4 SITL works fine.

Careful, HIL means hardware in the loop so by definition you need a pixhawk connected to be doing HIL simulations :wink:

**Comment by Mayankm96** [comment]
@andre-nguyen.. That's what I thought too! But so far I haven't connected the PX4 and it's running just fine for me :P

**Comment by andre-nguyen** [comment]
It's running "fine" because you aren't doing HIL, you are doing SITL. They are two different things.

**Comment by lovettchris** [comment]
I don't really agree with all these edits.  And it is too redundant with px4.md and sitl.md.  The xbox controller page was trying to provide only information relevant to setting up xbox controller.

**Pull request closed without merging**
