### PR TITLE
added sodacar

### PR DESCRIPTION
**Pull request by openweb**
soda lab is using AirSim.

http://sodacar.com

### CODE REVIEW

**Comment by madratman** [comment]
Hi @openweb. Can you share a demo video or something on that lines to share how you're using Airsim?

**Comment by openweb** [comment]
> 
> 
> Hi @openweb. Can you share a demo video or something on that lines to share how you're using Airsim?

**Comment by openweb** [comment]
> 
> 
> Hi @openweb. Can you share a demo video or something on that lines to share how you're using Airsim?

Hello @madratman I put a screenshot first and show a demo later.

**Comment by openweb** [comment]
Please reopen this unmerged commit.

**Pull request merged**
