### PR TITLE
Solve some random typos

### PR DESCRIPTION
**Pull request by patrickelectric**

### CODE REVIEW

**Comment by patrickelectric** [comment]
@msftclas done

**Comment by lovettchris** [comment]
Can you fix this code break?
struct HomeState { 
+		struct home state {

**Comment by patrickelectric** [comment]
@lovettchris done

**Comment by lovettchris** [comment]
Thanks for fixing those, in the future is is possible to squash your commits into one?  See [squashing](https://github.com/ginatrapani/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit).

**Comment by patrickelectric** [comment]
Can use `git rebase -i commit_id...` to squash all commits over commit_id.

**Pull request merged**
