### PR TITLE
Camera replaced by Cinematographic Camera (CinemAirSim)

### PR DESCRIPTION
**Pull request by ppueyor**
Fixes: #    
-Integrates the CineCameraComponent into AirSim

## About
An AddOn for AirSim that includes all the tools to integrate a cinematographic camera and the needed tools to control/access to it.
More info available in repo: https://github.com/ppueyor/CinemAirSim
Or conference paper: https://arxiv.org/abs/2003.07664

## How Has This Been Tested?
Ubuntu 20 and UE4 4.26
Different demos and API calls
Results available in repo

## Screenshots:
https://www.youtube.com/watch?v=OJGNaitWZVA

### CODE REVIEW

**Comment by ppueyor** [comment]
Hi, the checks need approval from the mantainers. Hope the last commit does the trick and passes the checks.

**Comment by ppueyor** [comment]
Hi, the checks need approval from the maintainers. Hope the last commit does the trick and passes the checks.

**Comment by ppueyor** [comment]
Hi, I fixed the last conflicts of this PR, but I still need a maintainer to check if it builds correctly. 

Thanks!

**Comment by ppueyor** [comment]
Hi, I fixed the last conflicts of this PR, but I still need a maintainer to check if it builds correctly.

Thanks!

**Comment by jonyMarino** [comment]
Hi @Pablo! Your PR seems to be failing at the block's packaging stage

**Comment by ppueyor** [comment]
Hi Jonathan! Thanks for your answer. It builds in the rest of the checks, right?

I use it in Ubuntu, play it in the blocks package and runs perfectly.
I don't know what happens.
How can I fix this issue?

Thanks again!

**Pull request closed without merging**
