### PR TITLE
SetSegmentationID assining wrong key

### PR DESCRIPTION
**Pull request by mustfkeskin**
Hello,

If I want to change segmentationId with regex there is logical problem.
First contains is not regex.

Second for example myRegex = Ground*
Contains command match some index but assingn wrong key.

If code change like below assign correct indices.

**Oldcode:** segmentationIds[objectName] = segmentationId;
**Newcode:** segmentationIds[s] = segmentationId;

### CODE REVIEW

**Review by ykpgrr — CHANGES_REQUESTED** [review]
I suggest you to be careful when submitting a Pull Request. You deleted one namespace (System.IO) and so many blank lines (the blank lines are necessary for clean code).
- You deleted `using System.IO` in line 4. You shouldn't.
- in line 63: there is extra `isNameRegex` --> `if (isNameRegex) {isNameRegex`
- in line 65: `keylist` should be `keyList` (upper case **L**) because the dictionary was initialized like `keyList`.

Thanks for your contribution, happy coding :)

**Review by ykpgrr — APPROVED** [review]
This changes seems to eliminate a bug which is caused for this situation:
let's assume:
`isNameRegex = True` , `objectName = "Ground"` and there is a key in "KeyList" Dictionary like "Ground_2" so `s="Ground_2"`.
The **bug** is that the code trying to change "Ground" in KeyList Dictionary. But there is no **key** like "Ground", it should be "Ground_2". This causes the code to fail. With changes 
`segmentationIds[objectName] = segmentationId;` as
`segmentationIds[s] = segmentationId;` **will be prevent this bug.**

On the other hand; I think there is still no regex in this algorithm although there is parameter for regex like `bool isNameRegex`. This can be another PR for this algorithm.

Happy coding :)

**Comment by howard-mahe** [comment]
Hi, this PR can be closed since PR #1859 has been merged.

**Comment by madratman** [comment]
thanks @howard-mahe !

**Pull request closed without merging**
