### PR TITLE
A basic tutorial on how to implement custom vehicles into the plugin

### PR DESCRIPTION
**Pull request by lukaszdworako**
I have created a tutorial that will assist in guiding someone through how to implement a custom vehicle into AirSim.

### CODE REVIEW

**Comment by sytelus** [comment]
Hi thanks for your contribution. Would it be possible to create .md file instead of docx to be consistent with rest of our documentation?

**Comment by nickylimjj** [comment]
Hi, I am trying to find a FBX format rover. Do you know where I can find one? Thank you.

**Comment by lukaszdworako** [comment]
@nickylimjj if you mean a four wheeled rover, one that I have been using is [this one](https://drive.google.com/open?id=0B2jqMoc9y9baWlJDRG04cDViY1U). If you make any progress on making it work properly let me know!

**Comment by nickylimjj** [comment]
@lukaszdworako will do!

**Pull request closed without merging**
