### PR TITLE
Yigal branch

### PR DESCRIPTION
**Pull request by yigalgru1**

### CODE REVIEW

**Comment by saihv** [comment]
Please add a description of what new features this PR introduces.

**Comment by madratman** [comment]
@yigalgru1 if you want this to be merged, it would be great if you can write a description what this PR does, why should we merge such an extensive change, and an overview of the workflow as well.

**Comment by madratman** [comment]
Reminder: `@yigalgru1 if you want this to be merged, it would be great if you can write a description what this PR does, why should we merge such an extensive change, and an overview of the workflow as well.`

**Comment by madratman** [comment]
@yigalgru1 I apologize, but I'm closing this due to a lack of response from your side to the maintainers' queries above. We're happy to accept new features and review PRs if we think they add value to the AirSim users. 
You may re-open this PR if and when you respond to our requests, and are finished working on it.
In addition, giving an outline of what this PR does and why is it useful will also help in getting feedback from users who might try it out before it gets merger.

**Pull request closed without merging**
