### PR TITLE
Gcc minor fixup

### PR DESCRIPTION
**Pull request by KerryMoffittRtn**

### CODE REVIEW

**Comment by lovettchris** [comment]
Thanks, but unfortunately this is crashing the VC++ compiler on Windows:
```
 d:\temp\airsim\mavlinkcom\common_utils\type_utils.hpp(50): fatal error C1001: An internal error has occurred in the compiler. [D:\temp\AirSim\MavLinkCom\MavLinkC
om.vcxproj]
```

**Comment by KerryMoffittRtn** [comment]
Wow, that's so surprising; I didn't touch anything that I thought would affect MavLinkCom, the commits obv passed Travis CI (though perhaps that doesn't cover Windows?), and everything works for me in VS2015 and 2017 (I'm currently on what I believe is the latest 2017: 15.9.13.)  Can you tell me what version of VS/VC++ exhibits this behavior?  Thanks!  (For the record, VS 15.9.13 reports using VC++ 2017 00369-60000-00001-AA412.)

**Comment by lovettchris** [comment]
anyway, I took your changes and went a bit further with it, see https://github.com/microsoft/AirSim/pull/2048

**Comment by KerryMoffittRtn** [comment]
Oh, excellent, thanks Chris!  :)

**Comment by madratman** [comment]
closing in favor of #2048 
bunch of re-typedefs in mavlinkmultirotorapi.hpp 
```
    typedef msr::airlib::GeoPoint GeoPoint; 
    typedef msr::airlib::VectorMath VectorMath; 
    typedef msr::airlib::Vector3r Vector3r; 
    typedef msr::airlib::Quaternionr Quaternionr; 
    typedef common_utils::Utils Utils; 
    typedef msr::airlib::real_T real_T;
```
and std::cosf , sinf v/s cos() sin() issues

**Pull request closed without merging**
