### PR TITLE
Fix GCC build

### LINKED ISSUE #2517: g++: error: unrecognized command line option ‘-stdlib=libc++
**When I run build.sh -gcc I get an error. Please tell me how to fix it. Airsim version = master
ubutnu = 18.04
g ++ gcc = 7.5
clang 9.0**

error : g++: error: unrecognized command line option ‘-stdlib=libc++’

**log**

./build.sh --gcc
+ MIN_GCC_VERSION=6.0.0
+ gccBuild=false
+ [[ 1 -gt 0 ]]
+ key=--gcc
+ case $key in
+ gccBuild=true
+ shift
+ [[ 0 -gt 0 ]]
+ '[' '!' -d ./external/rpclib/rpclib-2.2.1 ']'
+ '[' -d ./cmake_build ']'
++ which cmake
+ CMAKE=/usr/bin/cmake
+ true
+ build_dir=build_gcc_debug
+ which gcc
/usr/bin/gcc
++ gcc -dumpfullversion
+ gcc_ver=7.5.0
+ version_less_than_equal_to 7.5.0 6.0.0
++ printf '%s\n' 7.5.0 6.0.0
++ sort -V
++ head -n 1
+ test 6.0.0 = 7.5.0
+ export CC=gcc
+ CC=gcc
+ export CXX=g++
+ CXX=g++
+ [[ -d ./AirLib/deps/eigen3/Eigen ]]
+ echo 'putting build in build_gcc_debug folder, to clean, just delete the directory...'
putting build in build_gcc_debug folder, to clean, just delete the directory...
+ [[ -f ./cmake/CMakeCache.txt ]]
+ [[ -d ./cmake/CMakeFiles ]]
+ [[ ! -d build_gcc_debug ]]
+ pushd build_gcc_debug
++ nproc
+ make -j12
[  1%] Building CXX object MavLinkCom/CMakeFiles/MavLinkCom.dir/home/newdrone18/droneutil/AirSim/MavLinkCom/common_utils/ThreadUtils.cpp.o
[  2%] Building CXX object MavLinkCom/CMakeFiles/MavLinkCom.dir/home/newdrone18/droneutil/AirSim/MavLinkCom/common_utils/FileSystem.cpp.o
[  4%] Building CXX object MavLinkCom/CMakeFiles/MavLinkCom.dir/home/newdrone18/droneutil/AirSim/MavLinkCom/src/MavLinkConnection.cpp.o
[  5%] Building CXX object MavLinkCom/CMakeFiles/MavLinkCom.dir/home/newdrone18/droneutil/AirSim/MavLinkCom/src/AdHocConnection.cpp.o
[  7%] Building CXX object MavLinkCom/CMakeFiles/MavLinkCom.dir/home/newdrone18/droneutil/AirSim/MavLinkCom/src/MavLinkMessageBase.cpp.o
[  8%] Building CXX object MavLinkCom/CMakeFiles/MavLinkCom.dir/home/newdrone18/droneutil/AirSim/MavLinkCom/src/MavLinkLog.cpp.o
[ 10%] Building CXX object MavLinkCom/CMakeFiles/MavLinkCom.dir/home/newdrone18/droneutil/AirSim/MavLinkCom/src/MavLinkTcpServer.cpp.o
[ 11%] Building CXX object MavLinkCom/CMakeFiles/MavLinkCom.dir/home/newdrone18/droneutil/AirSim/MavLinkCom/src/MavLinkMessages.cpp.o
[ 13%] Building CXX object MavLinkCom/CMakeFiles/MavLinkCom.dir/home/newdrone18/droneutil/AirSim/MavLinkCom/src/MavLinkFtpClient.cpp.o
[ 14%] Building CXX object MavLinkCom/CMakeFiles/MavLinkCom.dir/home/newdrone18/droneutil/AirSim/MavLinkCom/src/MavLinkNode.cpp.o
g++: error: unrecognized command line option ‘-stdlib=libc++’
[ 16%] Building CXX object MavLinkCom/CMakeFiles/MavLinkCom.dir/home/newdrone18/droneutil/AirSim/MavLinkCom/src/MavLinkVehicle.cpp.o
MavLinkCom/CMakeFiles/MavLinkCom.dir/build.make:86: recipe for target 'MavLinkCom/CMakeFiles/MavLinkCom.dir/home/newdrone18/droneutil/AirSim/MavLinkCom/common_utils/ThreadUtils.cpp.o' failed
make[2]: *** [MavLinkCom/CMakeFiles/MavLinkCom.dir/home/newdrone18/droneutil/AirSim/MavLinkCom/common_utils/ThreadUtils.cpp.o] Error 1
g++: error: unrecognized command line option ‘-stdlib=libc++’
make[2]: *** Waiting for unfinished jobs....
MavLinkCom/CMakeFiles/MavLinkCom.dir/build.make:62: recipe for target 'MavLinkCom/CMakeFiles/MavLinkCom.dir/home/newdrone18/droneutil/AirSim/MavLinkCom/common_utils/FileSystem.cpp.o' failed
make[2]: *** [MavLinkCom/CMakeFiles/MavLinkCom.dir/home/newdrone18/droneutil/AirSim/MavLinkCom/common_utils/FileSystem.cpp.o] Error 1
g++: error: unrecognized command line option ‘-stdlib=libc++’
g++: error: unrecognized command line option ‘-stdlib=libc++’
g++: error: unrecognized command line option ‘-stdlib=libc++’
MavLinkCom/CMakeFiles/MavLinkCom.dir/build.make:110: recipe for target 'MavLinkCom/CMakeFiles/MavLinkCom.dir/home/newdrone18/droneutil/AirSim/MavLinkCom/src/AdHocConnection.cpp.o' failed
make[2]: *** [MavLinkCom/CMakeFiles/MavLinkCom.dir/home/newdrone18/droneutil/AirSim/MavLinkCom/src/AdHocConnection.cpp.o] Error 1
MavLinkCom/CMakeFiles/MavLinkCom.dir/build.make:134: recipe for target 'MavLinkCom/CMakeFiles/MavLinkCom.dir/home/newdrone18/droneutil/AirSim/MavLinkCom/src/MavLinkConnection.cpp.o' failed
make[2]: *** [MavLinkCom/CMakeFiles/MavLinkCom.dir/home/newdrone18/droneutil/AirSim/MavLinkCom/src/MavLinkConnection.cpp.o] Error 1
MavLinkCom/CMakeFiles/MavLinkCom.dir/build.make:206: recipe for target 'MavLinkCom/CMakeFiles/MavLinkCom.dir/home/newdrone18/droneutil/AirSim/MavLinkCom/src/MavLinkMessageBase.cpp.o' failed
make[2]: *** [MavLinkCom/CMakeFiles/MavLinkCom.dir/home/newdrone18/droneutil/AirSim/MavLinkCom/src/MavLinkMessageBase.cpp.o] Error 1
g++: error: unrecognized command line option ‘-stdlib=libc++’
MavLinkCom/CMakeFiles/MavLinkCom.dir/build.make:182: recipe for target 'MavLinkCom/CMakeFiles/MavLinkCom.dir/home/newdrone18/droneutil/AirSim/MavLinkCom/src/MavLinkLog.cpp.o' failed
make[2]: *** [MavLinkCom/CMakeFiles/MavLinkCom.dir/home/newdrone18/droneutil/AirSim/MavLinkCom/src/MavLinkLog.cpp.o] Error 1
g++: error: unrecognized command line option ‘-stdlib=libc++’
g++: error: unrecognized command line option ‘-stdlib=libc++’
g++: error: unrecognized command line option ‘-stdlib=libc++’
MavLinkCom/CMakeFiles/MavLinkCom.dir/build.make:230: recipe for target 'MavLinkCom/CMakeFiles/MavLinkCom.dir/home/newdrone18/droneutil/AirSim/MavLinkCom/src/MavLinkMessages.cpp.o' failed
make[2]: *** [MavLinkCom/CMakeFiles/MavLinkCom.dir/home/newdrone18/droneutil/AirSim/MavLinkCom/src/MavLinkMessages.cpp.o] Error 1
MavLinkCom/CMakeFiles/MavLinkCom.dir/build.make:158: recipe for target 'MavLinkCom/CMakeFiles/MavLinkCom.dir/home/newdrone18/droneutil/AirSim/MavLinkCom/src/MavLinkFtpClient.cpp.o' failed
make[2]: *** [MavLinkCom/CMakeFiles/MavLinkCom.dir/home/newdrone18/droneutil/AirSim/MavLinkCom/src/MavLinkFtpClient.cpp.o] Error 1
MavLinkCom/CMakeFiles/MavLinkCom.dir/build.make:278: recipe for target 'MavLinkCom/CMakeFiles/MavLinkCom.dir/home/newdrone18/droneutil/AirSim/MavLinkCom/src/MavLinkTcpServer.cpp.o' failed
make[2]: *** [MavLinkCom/CMakeFiles/MavLinkCom.dir/home/newdrone18/droneutil/AirSim/MavLinkCom/src/MavLinkTcpServer.cpp.o] Error 1
g++: error: unrecognized command line option ‘-stdlib=libc++’
MavLinkCom/CMakeFiles/MavLinkCom.dir/build.make:254: recipe for target 'MavLinkCom/CMakeFiles/MavLinkCom.dir/home/newdrone18/droneutil/AirSim/MavLinkCom/src/MavLinkNode.cpp.o' failed
make[2]: *** [MavLinkCom/CMakeFiles/MavLinkCom.dir/home/newdrone18/droneutil/AirSim/MavLinkCom/src/MavLinkNode.cpp.o] Error 1
g++: error: unrecognized command line option ‘-stdlib=libc++’
MavLinkCom/CMakeFiles/MavLinkCom.dir/build.make:302: recipe for target 'MavLinkCom/CMakeFiles/MavLinkCom.dir/home/newdrone18/droneutil/AirSim/MavLinkCom/src/MavLinkVehicle.cpp.o' failed
make[2]: *** [MavLinkCom/CMakeFiles/MavLinkCom.dir/home/newdrone18/droneutil/AirSim/MavLinkCom/src/MavLinkVehicle.cpp.o] Error 1
CMakeFiles/Makefile2:216: recipe for target 'MavLinkCom/CMakeFiles/MavLinkCom.dir/all' failed
make[1]: *** [MavLinkCom/CMakeFiles/MavLinkCom.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 17%] Building CXX object rpclib_wrapper/rpclib/CMakeFiles/rpc.dir/lib/rpc/dispatcher.cc.o
[ 19%] Building CXX object rpclib_wrapper/rpclib/CMakeFiles/rpc.dir/lib/rpc/this_session.cc.o
[ 22%] Building CXX object rpclib_wrapper/rpclib/CMakeFiles/rpc.dir/lib/rpc/server.cc.o
[ 22%] Building CXX object rpclib_wrapper/rpclib/CMakeFiles/rpc.dir/lib/rpc/client.cc.o
[ 23%] Building CXX object rpclib_wrapper/rpclib/CMakeFiles/rpc.dir/lib/rpc/this_server.cc.o
[ 25%] Building CXX object rpclib_wrapper/rpclib/CMakeFiles/rpc.dir/lib/rpc/this_handler.cc.o
g++: error: unrecognized command line option ‘-stdlib=libc++’
rpclib_wrapper/rpclib/CMakeFiles/rpc.dir/build.make:62: recipe for target 'rpclib_wrapper/rpclib/CMakeFiles/rpc.dir/lib/rpc/dispatcher.cc.o' failed
make[2]: *** [rpclib_wrapper/rpclib/CMakeFiles/rpc.dir/lib/rpc/dispatcher.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 26%] Building CXX object rpclib_wrapper/rpclib/CMakeFiles/rpc.dir/lib/rpc/detail/server_session.cc.o
[ 27%] Building CXX object rpclib_wrapper/rpclib/CMakeFiles/rpc.dir/lib/rpc/detail/client_error.cc.o
g++: error: unrecognized command line option ‘-stdlib=libc++’
[ 29%] Building CXX object rpclib_wrapper/rpclib/CMakeFiles/rpc.dir/lib/rpc/detail/response.cc.o
rpclib_wrapper/rpclib/CMakeFiles/rpc.dir/build.make:158: recipe for target 'rpclib_wrapper/rpclib/CMakeFiles/rpc.dir/lib/rpc/this_session.cc.o' failed
make[2]: *** [rpclib_wrapper/rpclib/CMakeFiles/rpc.dir/lib/rpc/this_session.cc.o] Error 1
g++: error: unrecognized command line option ‘-stdlib=libc++’
g++: error: unrecognized command line option ‘-stdlib=libc++’
g++: error: unrecognized command line option ‘-stdlib=libc++’
rpclib_wrapper/rpclib/CMakeFiles/rpc.dir/build.make:86: recipe for target 'rpclib_wrapper/rpclib/CMakeFiles/rpc.dir/lib/rpc/server.cc.o' failed
make[2]: *** [rpclib_wrapper/rpclib/CMakeFiles/rpc.dir/lib/rpc/server.cc.o] Error 1
rpclib_wrapper/rpclib/CMakeFiles/rpc.dir/build.make:110: recipe for target 'rpclib_wrapper/rpclib/CMakeFiles/rpc.dir/lib/rpc/client.cc.o' failed
make[2]: *** [rpclib_wrapper/rpclib/CMakeFiles/rpc.dir/lib/rpc/client.cc.o] Error 1
rpclib_wrapper/rpclib/CMakeFiles/rpc.dir/build.make:134: recipe for target 'rpclib_wrapper/rpclib/CMakeFiles/rpc.dir/lib/rpc/this_handler.cc.o' failed
make[2]: *** [rpclib_wrapper/rpclib/CMakeFiles/rpc.dir/lib/rpc/this_handler.cc.o] Error 1
g++: error: unrecognized command line option ‘-stdlib=libc++’
rpclib_wrapper/rpclib/CMakeFiles/rpc.dir/build.make:182: recipe for target 'rpclib_wrapper/rpclib/CMakeFiles/rpc.dir/lib/rpc/this_server.cc.o' failed
make[2]: *** [rpclib_wrapper/rpclib/CMakeFiles/rpc.dir/lib/rpc/this_server.cc.o] Error 1
[ 30%] Building CXX object rpclib_wrapper/rpclib/CMakeFiles/rpc.dir/lib/rpc/rpc_error.cc.o
[ 32%] Building CXX object rpclib_wrapper/rpclib/CMakeFiles/rpc.dir/dependencies/src/format.cc.o
[ 33%] Building CXX object rpclib_wrapper/rpclib/CMakeFiles/rpc.dir/lib/rpc/nonstd/optional.cc.o
g++: error: unrecognized command line option ‘-stdlib=libc++’
rpclib_wrapper/rpclib/CMakeFiles/rpc.dir/build.make:230: recipe for target 'rpclib_wrapper/rpclib/CMakeFiles/rpc.dir/lib/rpc/detail/server_session.cc.o' failed
make[2]: *** [rpclib_wrapper/rpclib/CMakeFiles/rpc.dir/lib/rpc/detail/server_session.cc.o] Error 1
g++: error: unrecognized command line option ‘-stdlib=libc++’
rpclib_wrapper/rpclib/CMakeFiles/rpc.dir/build.make:278: recipe for target 'rpclib_wrapper/rpclib/CMakeFiles/rpc.dir/lib/rpc/detail/client_error.cc.o' failed
make[2]: *** [rpclib_wrapper/rpclib/CMakeFiles/rpc.dir/lib/rpc/detail/client_error.cc.o] Error 1
g++: error: unrecognized command line option ‘-stdlib=libc++’
rpclib_wrapper/rpclib/CMakeFiles/rpc.dir/build.make:254: recipe for target 'rpclib_wrapper/rpclib/CMakeFiles/rpc.dir/lib/rpc/detail/response.cc.o' failed
make[2]: *** [rpclib_wrapper/rpclib/CMakeFiles/rpc.dir/lib/rpc/detail/response.cc.o] Error 1
g++: error: unrecognized command line option ‘-stdlib=libc++’
g++: error: unrecognized command line option ‘-stdlib=libc++’
g++: error: unrecognized command line option ‘-stdlib=libc++’
rpclib_wrapper/rpclib/CMakeFiles/rpc.dir/build.make:326: recipe for target 'rpclib_wrapper/rpclib/CMakeFiles/rpc.dir/dependencies/src/format.cc.o' failed
make[2]: *** [rpclib_wrapper/rpclib/CMakeFiles/rpc.dir/dependencies/src/format.cc.o] Error 1
rpclib_wrapper/rpclib/CMakeFiles/rpc.dir/build.make:206: recipe for target 'rpclib_wrapper/rpclib/CMakeFiles/rpc.dir/lib/rpc/rpc_error.cc.o' failed
make[2]: *** [rpclib_wrapper/rpclib/CMakeFiles/rpc.dir/lib/rpc/rpc_error.cc.o] Error 1
rpclib_wrapper/rpclib/CMakeFiles/rpc.dir/build.make:302: recipe for target 'rpclib_wrapper/rpclib/CMakeFiles/rpc.dir/lib/rpc/nonstd/optional.cc.o' failed
make[2]: *** [rpclib_wrapper/rpclib/CMakeFiles/rpc.dir/lib/rpc/nonstd/optional.cc.o] Error 1
CMakeFiles/Makefile2:103: recipe for target 'rpclib_wrapper/rpclib/CMakeFiles/rpc.dir/all' failed
make[1]: *** [rpclib_wrapper/rpclib/CMakeFiles/rpc.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**When I run build.sh -gcc I get an error. Please tell me how to fix it. Airsim version = master
ubutnu = 18.04
g ++ gcc = 7.5
clang 9.0**

### PR DESCRIPTION
**Pull request by rajat2004**
Upgrade min GCC version to 8.0.0 - required for `#include <filesystem>`
Closes https://github.com/microsoft/AirSim/issues/2517

Should GCC build be added to Travis?

### CODE REVIEW

**Comment by madratman** [comment]
Hmm, this doesn't completely fix it. AirLib compiles fine with gcc with your PR, but if you build the unreal project, there are N thousand number of undefined symbol errors.

**Comment by rajat2004** [comment]
Yes, that is there. I hadn't checked it while opening the PR since was reinstalling UE at that time
Did the Unreal project work properly earlier with gcc earlier?

**Comment by madratman** [comment]
It seems like the removal of custom libcxx in my previous PR will force us to use clang. 
we'll have to do something like - https://libcxx.llvm.org/docs/UsingLibcxx.html#using-libc-with-gcc I think
`-I<libcxx-install-prefix>/include/c++/v1` seems to be `/usr/include/c++/8/`
trying it out

**Comment by madratman** [comment]
yeah, it worked as the libcxx was build manually and the right paths were included

**Comment by rajat2004** [comment]
Great! Could you push your commit onto my branch, will try it out

**Comment by madratman** [comment]
I was responding to ` Did the Unreal project work properly earlier with gcc earlier?`, not that I made it work.. wip. will update. I think I got the includes correct, no adding linkers

**Comment by rajat2004** [comment]
> Either way, sounds like we're in a sweet spot for one of those gory linking hells...

Oh yeah, we're there. Spent about half-hour trying different linking flags, orders. Nothing worked, then things went from bad to worse

**Comment by rajat2004** [comment]
> yeah, it worked as the libcxx was build manually and the right paths were included

So, for GCC build, then we'll need to build libcxx from source with GCC and then include those files?
I'm at a loss at other things to try, since linker isn't cooperating at all

**Comment by madratman** [comment]
It seems to me we have to drop gcc build if this doesn't get resolved.
In general, am not sure what value it's adding.

**Comment by rajat2004** [comment]
One place I think this might be needed is when using ROS, which uses GCC only
Just a thought, not sure about this though

**Comment by rajat2004** [comment]
Did try a lot of things to get this to work, but still, heaps of linking errors
Also tried a manual build of libcxx but didn't work - https://github.com/rajat2004/AirSim/tree/gcc-libcxx

@madratman I think the earlier GCC build didn't use the LLVM built from source, from the lines removed in https://github.com/microsoft/AirSim/pull/2500, that is only included when it's using Clang, rather than GCC
Maybe it's a problem with c++17 version, Google is also not helping much

**Comment by madratman** [comment]
> One place I think this might be needed is when using ROS, which uses GCC only
We can add that on the ROS' CMakeLists.txt as done in https://github.com/microsoft/AirSim/pull/2571. It's essentially the same thing as my last commit in this PR, but on the ROS side. 
 
I'd vote to to either add a line in doc that gcc build option is for AirLib standalone lib only and not for Unreal project, 
or remove the gcc option altogether (along with documentation line) in another PR and close this one.

**Comment by rajat2004** [comment]
Yup, removing GCC build altogether makes more sense, with ROS project built with GCC
Will test that out, and then open another PR to remove all gcc bits

**Pull request closed without merging**
