### PR TITLE
[docs] Update CHANGELOG.md

### PR DESCRIPTION
**Pull request by rajat2004**
As mentioned in the Changelog, only keeping the bigger updates, not including bug-fixes, etc.

### CODE REVIEW

**Comment by rajat2004** [comment]
There's a [What's New](https://github.com/microsoft/AirSim#whats-new) section in the main Readme, details from that will need to be included. Should that be kept or just point to Changelog?

**Comment by madratman** [comment]
Please remove whitespace changes in the diff - https://stackoverflow.com/questions/3515597/add-only-non-whitespace-changes. 
What's new should have the key highlights

**Comment by rajat2004** [comment]
So the current changes to What's new are okay? And then some more detailed info to Changelog such as imp bug fixes?

**Comment by rajat2004** [comment]
Removed the whitespace changes (need to fix that in some other PRs as well)
Will add some other bug-fixes, etc in Changelog

**Comment by rajat2004** [comment]
I think the current list should be enough, for more details, the commit list is always there

**Comment by rajat2004** [comment]
Looks okay to me, Changelog now has info about changes in April as well

**Comment by madratman** [comment]
" * [Support for PX4 master](https://microsoft.github.io/AirSim/px4_setup/) " -> this is incorrect. 
we support v1.10 now. Chris is working on the master support in the latest PR.

**Comment by rajat2004** [comment]
@madratman Fixed, when I wrote this, I thought it was working with the master branch as well
Changelog now includes changes till today as well

**Pull request merged**
