### PR TITLE
add wrapper for line of sight APIs

### PR DESCRIPTION
**Pull request by zimmy87**
Fixes: n/a

## About
This PR adds wrappers for simTestLineOfSightToPoint, simTestLineOfSightBetweenPoints, and simGetWorldExtents. It also adds an example script for calling these APIs.

## How Has This Been Tested?
Example script was called and output was sanity checked.

## Screenshots (if appropriate):

### CODE REVIEW

**Comment by rajat2004** [comment]
Isn't it cleaner to use `GeoPoint` directly instead of separate lat, lon & alt?

**Comment by zimmy87** [comment]
good point @rajat2004, I've updated the python wrapper as well as the original APIs to use GeoPoint parameters instead of separate lat, lon & alt parameters.

**Comment by rajat2004** [comment]
Also, this is somewhat separate from this PR but the `simGetWorldExtents` & `simTestLineOfSightBetweenPoints` APIs are better suited in WorldSimApi.cpp rather than PawnSimApi IMHO since they both don't deal with vehicles at all. 
Their actual implementation can use the wrapper `RunCommandOnGameThread` instead of the FTaskGraph stuff, there's a bit of code duplication between `simTestLineOfSightBetweenPoints` & `simTestLineOfSightToPoint` also, the latter could call the former but that'll be likely bit painful to implement. Just some things which jumped out to me when looking at the code

**Comment by zimmy87** [comment]
Thanks @rajat2004 for the suggestions. I think we are going to implement those changes in a separate PR.

**Pull request merged**
