### PR TITLE
Optical flow camera

### PR DESCRIPTION
**Pull request by saihv**
## About

Adds an optical flow camera that computes pixel velocity through a material/HLSL code. Inspired by https://github.com/carla-simulator/carla/pull/4104, and the discussion at https://github.com/EpicGames/UnrealEngine/pull/6933 (thanks to @finger563 for the discussion and useful code!)

This PR does not make use of UE's native velocity buffer due to issues in its calculation of motion vectors (see https://github.com/EpicGames/UnrealEngine/pull/6933), and hence, can only compute optical flow based on camera motion and not dynamic objects. This is meant as an intermediate step while UE fixes the issues with velocity buffer (more discussion at https://github.com/florian-world/VelocityUE4).

The flow data is exposed in two ways, through two new 'cameras': 

1. OpticalFlowCaptureComponent returns a 2-channel image where the channels correspond to vx and vy respectively. Corresponding material: HUDAssets/OpticalFlowMaterial.
2. OpticalFlowVisCaptureComponent is the other camera which converts the flow data to RGB for a more 'visual' output. Corresponding material: HUDAssets/OpticalFlowRGBMaterial.

## How Has This Been Tested?
The two new cameras can be targeted through their ids 8 and 9; and can be visualized either through subwindows or through the normal Python image request API. 

Pending accuracy tests of per-pixel flow.

## Screenshots (if appropriate):

https://user-images.githubusercontent.com/2274262/128618769-2df2d944-2b65-4638-9d47-39fe912d5450.mp4

### CODE REVIEW

**Comment by jonyMarino** [comment]
@saihv What is the difference between OpticalFlow and OpticalFlowVis?

**Comment by saihv** [comment]
@jonyMarino 

OpticalFlow is a 2-channel image where the channels correspond to vx and vy respectively (camera optical flow velocity). This is the data that is the actual raw optical flow. Corresponding material: HUDAssets/OpticalFlowMaterial.
OpticalFlowVis is a modified version that converts the flow data to RGB for a more 'visual' output that is easy to understand. Corresponding material: HUDAssets/OpticalFlowRGBMaterial.

**Comment by zimmy87** [comment]
Tested locally and it works for me; thanks for the contribution @saihv!

**Comment by alonfaraj** [comment]
Hi @saihv,
This is a great feature, thanks!
Maybe it's worth update the [documentation ](https://microsoft.github.io/AirSim/image_apis/#available-imagetype-values), as well as the ros wrapper code.

**Comment by KaiXin-Chen** [comment]
Hi, 
  Thanks for the great functionality. However, there are something that I don't quite understand about it, mind giving me some clue on this?

1) If we store optical flow in the format of png ( using the argument  PixelsAsFloat= false). it doesn't make sense for me of saving optical flow information in the format of uint8 (as optical flow can be negitive and should be a float) 

2) If we store it using .pfm (PixelsAsFloat= true), the pfm file only have one channel, which also doesn't make sense to me.

  Mind letting me know what I did wrong? Thanks a lot !

**Comment by artths** [comment]
> Hi, Thanks for the great functionality. However, there are something that I don't quite understand about it, mind giving me some clue on this?
> 
> 1. If we store optical flow in the format of png ( using the argument  PixelsAsFloat= false). it doesn't make sense for me of saving optical flow information in the format of uint8 (as optical flow can be negitive and should be a float)
> 2. If we store it using .pfm (PixelsAsFloat= true), the pfm file only have one channel, which also doesn't make sense to me.
> 
> Mind letting me know what I did wrong? Thanks a lot !

It's not about storing. Response itself seem to have only 1 channel. This feature is broken.

**Comment by kaillerC94** [comment]
> Hi, Thanks for the great functionality. However, there are something that I don't quite understand about it, mind giving me some clue on this?
> 
> 1. If we store optical flow in the format of png ( using the argument  PixelsAsFloat= false). it doesn't make sense for me of saving optical flow information in the format of uint8 (as optical flow can be negitive and should be a float)
> 2. If we store it using .pfm (PixelsAsFloat= true), the pfm file only have one channel, which also doesn't make sense to me.
> 
> Mind letting me know what I did wrong? Thanks a lot !

Still encounter this problem in 2024. Did you solve it later?

**Pull request merged**
