### PR TITLE
Fix some PX4 issues with latest master branch

### PR DESCRIPTION
**Pull request by lovettchris**
Fix memory corruption in setThreadName helper function.
Print message when home GPS location is set.
Delay connecting UDP connection to avoid socket errors.

### CODE REVIEW

**Comment by rajat2004** [comment]
One thing which I had noticed sometime back is that PX4 is using the [system clock](https://github.com/microsoft/AirSim/blob/master/AirLib/include/vehicles/multirotor/firmwares/mavlink/MavLinkMultirotorApi.hpp#L1309) for sending the simulation time. This is in contrast to in Ardupilot where the [stepped time](https://github.com/microsoft/AirSim/blob/master/AirLib/include/vehicles/multirotor/firmwares/arducopter/ArduCopterApi.hpp#L407) is being used

I really have no idea whether this causes any effect or anything, just though I should post my doubt

**Comment by lovettchris** [comment]
Interesting question about the clock, I'll ping my PX4 friends and see if the actual time delta between ticks makes any difference when PX4 is running in lockstep mode.  I doubt it will, but I'll check, thanks.

**Comment by madratman** [comment]
This seems to be working well with master, v1.11.0-beta1, v.10.1. @TomSeestern, @bys1123, it would be great if you guys can give it a shot as well. (I haven't tried sending cmds with QGC). Just observing the terminal output

**Comment by bys1123** [comment]
Thanks your great works! 
cc' @Jaeyoung-Lim @MaEtUgR

**Pull request merged**
