### PR TITLE
Added Octo X config

### PR DESCRIPTION
**Pull request by aaqibismail**
Fixes: #    

#3593 

## About

Added an Octo X rotor configuration for PX4 devices. The rotor poses were calculated according to NED's left hand rule.

## How Has This Been Tested?

I changed the model in settings.json to "Octocopter" and adjusted the SITL none_iris PX4 target to use an octo_x mixer file. I tested with both a controller and a python script and ensured that not only did it fly smoothly, but that there were 8 actuator outputs.

## Screenshots (if appropriate):

### CODE REVIEW

**Comment by zimmy87** [comment]
It seems that your PR is failing the clang-format check. Please follow these steps to resolve this:

1. check out your pull request
2. run `git checkout master .clang-format` in your repo's root folder
3. if you don't have npm installed, download it from https://www.npmjs.com/get-npm
4. run `npm install -g clang-format`
5. run `clang-format -i path/to/file` for each failing file
6. run `git add -u` to track all style changes
7. run `git commit -am "apply style from clang-format"`
8. run `git merge master`
9. resolve other non-style conflicts if you have any
10. push changes

Thanks for helping us with these style changes!

**Comment by zimmy87** [comment]
Hi @aaqibism! Were you testing this PR with a specific mesh for your octocopter? If so, is this mesh publicly available somewhere?

**Comment by aaqibism** [comment]
> Hi @aaqibism! Were you testing this PR with a specific mesh for your octocopter? If so, is this mesh publicly available somewhere?

I tested with the default quad mesh.

**Comment by zimmy87** [comment]
Thanks for the contribution @aaqibism! Tested with commander and python script; looks to be working for me so I am moving ahead with merge.

**Pull request merged**
