### PR TITLE
[Travis] Add ROS compilation test, dependencies script

### PR DESCRIPTION
**Pull request by rajat2004**
Came to mind when working on #2710

Should the AirSim dependencies be separated into a different script? Don't think there's much of a need for this, but let me know if that's better

### CODE REVIEW

**Comment by rajat2004** [comment]
Should we separate the AirSim dependencies into a different script?

**Comment by rajat2004** [comment]
@saihv Could you have a look at this?

**Comment by madratman** [comment]
lgtm, thanks!

**Comment by rajat2004** [comment]
Thanks for merging!

**Pull request merged**
