### PR TITLE
Add OSX compiler support

### PR DESCRIPTION
**Pull request by 8W9aG**
This introduces some minor changes which enables AirSim to be compiled on OSX successfully.

Tested on:
Xcode 8.2.1
OSX 10.12.3

I have yet to test whether this works, but thought I'd get that going after this is in.

### CODE REVIEW

**Comment by lovettchris** [comment]
Thanks!

**Comment by lovettchris** [comment]
Now you can test it by following these instructions: https://youtu.be/HNWdYrtw3f0

**Comment by lovettchris** [comment]
Hey can you also do the cla thing? Thanks.

**Comment by d13-kevinf** [comment]
Can you include the proper linking for OS X ? 

1 warning generated.
[100%] Linking CXX executable DroneShell
ld: warning: ignoring file /tmp/AirSim/AirLib/deps/rpclib/lib/x64/linux/librpc.a, file was built for archive which is not the architecture being linked (x86_64): /tmp/AirSim/AirLib/deps/rpclib/lib/x64/linux/librpc.a
Undefined symbols for architecture x86_64:
  "rpc::client::get_next_call_idx()", referenced from:
      std::__1::future<clmdep_msgpack::v1::object_handle> rpc::client::async_call<bool>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool) in libAirLib.a(RpcLibClient.cpp.o)
      std::__1::future<clmdep_msgpack::v1::object_handle> rpc::client::async_call<>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in libAirLib.a(RpcLibClient.cpp.o)
      std::__1::future<clmdep_msgpack::v1::object_handle> rpc::client::async_call<float>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, float) in libAirLib.a(RpcLibClient.cpp.o)
      std::__1::future<clmdep_msgpack::v1::object_handle> rpc::client::async_call<float, float, float, float, float>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, float, float, float, float, float) in libAirLib.a(RpcLibClient.cpp.o)
      std::__1::future<clmdep_msgpack::v1::object_handle> rpc::client::async_call<float, float, float, float, msr::airlib::DrivetrainType, msr::airlib_rpclib::RpcLibAdapators::YawMode>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, float, float, float, float, msr::airlib::DrivetrainType, msr::airlib_rpclib::RpcLibAdapators::YawMode) in libAirLib.a(RpcLibClient.cpp.o)
      std::__1::future<clmdep_msgpack::v1::object_handle> rpc::client::async_call<std::__1::vector<msr::airlib_rpclib::RpcLibAdapators::Vector3r, std::__1::allocator<msr::airlib_rpclib::RpcLibAdapators::Vector3r> >, float, msr::airlib::DrivetrainType, msr::airlib_rpclib::RpcLibAdapators::YawMode, float, float>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::vector<msr::airlib_rpclib::RpcLibAdapators::Vector3r, std::__1::allocator<msr::airlib_rpclib::RpcLibAdapators::Vector3r> >, float, msr::airlib::DrivetrainType, msr::airlib_rpclib::RpcLibAdapators::YawMode, float, float) in libAirLib.a(RpcLibClient.cpp.o)
      std::__1::future<clmdep_msgpack::v1::object_handle> rpc::client::async_call<float, float, float, float, msr::airlib::DrivetrainType, msr::airlib_rpclib::RpcLibAdapators::YawMode, float, float>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, float, float, float, float, msr::airlib::DrivetrainType, msr::airlib_rpclib::RpcLibAdapators::YawMode, float, float) in libAirLib.a(RpcLibClient.cpp.o)
      ...
  "rpc::client::post(std::__1::shared_ptr<clmdep_msgpack::v1::sbuffer>, int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<std::__1::promise<clmdep_msgpack::v1::object_handle> >)", referenced from:
      std::__1::future<clmdep_msgpack::v1::object_handle> rpc::client::async_call<bool>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool) in libAirLib.a(RpcLibClient.cpp.o)
      std::__1::future<clmdep_msgpack::v1::object_handle> rpc::client::async_call<>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in libAirLib.a(RpcLibClient.cpp.o)
      std::__1::future<clmdep_msgpack::v1::object_handle> rpc::client::async_call<float>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, float) in libAirLib.a(RpcLibClient.cpp.o)
      std::__1::future<clmdep_msgpack::v1::object_handle> rpc::client::async_call<float, float, float, float, float>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, float, float, float, float, float) in libAirLib.a(RpcLibClient.cpp.o)
      std::__1::future<clmdep_msgpack::v1::object_handle> rpc::client::async_call<float, float, float, float, msr::airlib::DrivetrainType, msr::airlib_rpclib::RpcLibAdapators::YawMode>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, float, float, float, float, msr::airlib::DrivetrainType, msr::airlib_rpclib::RpcLibAdapators::YawMode) in libAirLib.a(RpcLibClient.cpp.o)
      std::__1::future<clmdep_msgpack::v1::object_handle> rpc::client::async_call<std::__1::vector<msr::airlib_rpclib::RpcLibAdapators::Vector3r, std::__1::allocator<msr::airlib_rpclib::RpcLibAdapators::Vector3r> >, float, msr::airlib::DrivetrainType, msr::airlib_rpclib::RpcLibAdapators::YawMode, float, float>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::vector<msr::airlib_rpclib::RpcLibAdapators::Vector3r, std::__1::allocator<msr::airlib_rpclib::RpcLibAdapators::Vector3r> >, float, msr::airlib::DrivetrainType, msr::airlib_rpclib::RpcLibAdapators::YawMode, float, float) in libAirLib.a(RpcLibClient.cpp.o)
      std::__1::future<clmdep_msgpack::v1::object_handle> rpc::client::async_call<float, float, float, float, msr::airlib::DrivetrainType, msr::airlib_rpclib::RpcLibAdapators::YawMode, float, float>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, float, float, float, float, msr::airlib::DrivetrainType, msr::airlib_rpclib::RpcLibAdapators::YawMode, float, float) in libAirLib.a(RpcLibClient.cpp.o)
      ...
  "rpc::client::wait_conn()", referenced from:
      std::__1::future<clmdep_msgpack::v1::object_handle> rpc::client::async_call<bool>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool) in libAirLib.a(RpcLibClient.cpp.o)
      std::__1::future<clmdep_msgpack::v1::object_handle> rpc::client::async_call<>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in libAirLib.a(RpcLibClient.cpp.o)
      std::__1::future<clmdep_msgpack::v1::object_handle> rpc::client::async_call<float>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, float) in libAirLib.a(RpcLibClient.cpp.o)
      std::__1::future<clmdep_msgpack::v1::object_handle> rpc::client::async_call<float, float, float, float, float>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, float, float, float, float, float) in libAirLib.a(RpcLibClient.cpp.o)
      std::__1::future<clmdep_msgpack::v1::object_handle> rpc::client::async_call<float, float, float, float, msr::airlib::DrivetrainType, msr::airlib_rpclib::RpcLibAdapators::YawMode>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, float, float, float, float, msr::airlib::DrivetrainType, msr::airlib_rpclib::RpcLibAdapators::YawMode) in libAirLib.a(RpcLibClient.cpp.o)
      std::__1::future<clmdep_msgpack::v1::object_handle> rpc::client::async_call<std::__1::vector<msr::airlib_rpclib::RpcLibAdapators::Vector3r, std::__1::allocator<msr::airlib_rpclib::RpcLibAdapators::Vector3r> >, float, msr::airlib::DrivetrainType, msr::airlib_rpclib::RpcLibAdapators::YawMode, float, float>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::vector<msr::airlib_rpclib::RpcLibAdapators::Vector3r, std::__1::allocator<msr::airlib_rpclib::RpcLibAdapators::Vector3r> >, float, msr::airlib::DrivetrainType, msr::airlib_rpclib::RpcLibAdapators::YawMode, float, float) in libAirLib.a(RpcLibClient.cpp.o)
      std::__1::future<clmdep_msgpack::v1::object_handle> rpc::client::async_call<float, float, float, float, msr::airlib::DrivetrainType, msr::airlib_rpclib::RpcLibAdapators::YawMode, float, float>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, float, float, float, float, msr::airlib::DrivetrainType, msr::airlib_rpclib::RpcLibAdapators::YawMode, float, float) in libAirLib.a(RpcLibClient.cpp.o)
      ...
  "rpc::client::client(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned short)", referenced from:
      msr::airlib::RpcLibClient::impl::impl(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned short) in libAirLib.a(RpcLibClient.cpp.o)
  "rpc::client::~client()", referenced from:
      msr::airlib::RpcLibClient::impl::~impl() in libAirLib.a(RpcLibClient.cpp.o)
  "typeinfo for rpc::rpc_error", referenced from:
      main::$_0::operator()(std::exception&) const in main.cpp.o
      GCC_except_table1287 in main.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [DroneShell/DroneShell] Error 1
make[1]: *** [DroneShell/CMakeFiles/DroneShell.dir/all] Error 2

**Comment by 8W9aG** [comment]
Sorry about that I was just compiling the AirLib library, I'll fix the linking issues on the HelloDrone target pronto

**Comment by d13-kevinf** [comment]
Don't be sorry! Thanks for what you have done thus far. Seeing it hit 100% made me grin.

**Comment by 8W9aG** [comment]
Fix here: https://github.com/Microsoft/AirSim/pull/16

**Comment by lzl200102109** [comment]
I am trying to compile the code using cmake. I installed all the prerequisites and did a git submodule update to clone the external/rpclib.

But then when I ran build.sh under the cmake folder, it gives me an error saying that

```
CMake Error at CMakeLists.txt:4 (add_subdirectory):
  add_subdirectory given source "{AIRSIM_ROOT}/external/rpclib" which is not
  an existing directory.


CMake Error at CMakeLists.txt:5 (ADD_CUSTOM_COMMAND):
  No TARGET 'rpc' has been created in this directory.
```

Did anyone have this issue? How do I solve it?

**Comment by sytelus** [comment]
Aha... first you need to get rpclib submodule. 

`git submodule update --init --recursive`

BTW, there is a bug in CMakeLists.txt. We need to make AirLib dependent on rpclib. Please feel free to change. I've get my Linux m/c ready for testing this first...

**Comment by lzl200102109** [comment]
@sytelus I followed your instruction and ran this line in a brand new clone of AirSim.
```
git submodule update --init --recursive
```
But I still get the same error as before. I have Eigen, Boost, and gcc/g++6 installed and detected properly.

And how do I fix the CMakeLists.txt, to make AirLib dependent on rpclib? I am not very good with cmake.

Thank you! I am very excited about this, and really want to try it out.

**Comment by lovettchris** [comment]
I'm working on fixing this right now, stay tuned...

**Pull request merged**
