### PR TITLE
Control manual camera speed through the keyboard

### PR DESCRIPTION
**Pull request by saihv**
### About
This PR allows for changing the speed of the manual camera through the LShift (faster) and LCtrl (slower) keys. Particularly of use in the computer vision mode.

### How Has This Been Tested?
Open AirSim in Computer Vision mode/enter manual camera mode using `M`, and then use `LShift` and `LCtrl` to increase/decrease camera speed.

### CODE REVIEW

**Comment by chickenbestlover** [comment]
I've been waiting for this feature for a long time. Thank you.

**Comment by jonyMarino** [comment]
We need to update the docs too

**Comment by zimmy87** [comment]
Applied clang-format  and merged with master locally, the new controls still worked as expected so I am moving ahead with merging this.

**Comment by h-gokul** [comment]
The manual camera speed settings for the computer vision mode are working great with translational motion, but I dont think there is such a setting for angular motion. Are there any plans of introducing this feature?  This setting seems to be very crucial for collecting high fps data for our research with certain indoor environments, where spawn drones/cars is unsuitable.

**Comment by jonyMarino** [comment]
Hi @h-gokul! Not in our plans. It depends on community contributions.

**Pull request merged**
