### PR TITLE
Add cross-platform support for Unity

### PR DESCRIPTION
**Pull request by msb336**

### CODE REVIEW

**Comment by madratman** [comment]
@msb336 can you add these images for clarity in the install process
https://drive.google.com/drive/folders/1Yui0C46YSMV6-SM3_SWc4Quw34bKN8km?usp=sharing

**Comment by madratman** [comment]
@msb336 can you also plz add a link to download unity for ubuntu. 
Their forum is hard to find and then you have to scroll to page 2 to actually find a link
https://forum.unity.com/threads/unity-on-linux-release-notes-and-known-issues.350256/

**Comment by madratman** [comment]
Can you a put a direct link to unity for linux download in the readme. 
Finding it on the second page of the forum is pretty hard - https://forum.unity.com/threads/unity-on-linux-release-notes-and-known-issues.350256/

For 2018.2.7f1 (that's what I am testing it with)
We should add this to readme:
- `wget -c https://beta.unity3d.com/download/dad990bf2728/UnitySetup-2018.2.7f1` 
- `chmod +x UnitySetup-2018.2.7f1`
- `sudo ./UnitySetup-2018.2.7f1`.

**Comment by msb336** [comment]
Did you need Unity Editor to run the standalone binaries? If so, that's a problem.
This release is to use Binaries created in *windows*, not to run natively in the editor in linux.

**Comment by msb336** [comment]
@jasonhbartlett Good catch! I was using an outdated version of the Unity port, and this editor failsafe didn't exist yet.

**Pull request merged**
