### PR TITLE
Convert line breaks

### PR DESCRIPTION
**Pull request by zimmy87**
Fixes: n/a    

## About

update CRLF to LF line breaks

## Screenshots (if appropriate):

### CODE REVIEW

**Comment by rajat2004** [comment]
TBH I don't really see the point of this mass formatting. Agree that having a common line break will be good, but this will again lead to mass conflicts and problems with the git history. The clang formatting made the code more readable and enforced common styles, but this doesn't really add any such benefits. Again, up to you and the maintainers though

**Comment by jonyMarino** [comment]
> TBH I don't really see the point of this mass formatting. Agree that having a common line break will be good, but this will again lead to mass conflicts and problems with the git history. The clang formatting made the code more readable and enforced common styles, but this doesn't really add any such benefits. Again, up to you and the maintainers though
> 
> Also, if this does go through, it'll be best to ensure this is enforced, probably through clang-format itself

@rajat2004, Do you know if git doesn't resolve conflicts for line break format automatically?

**Comment by rajat2004** [comment]
Well, it's kind of a mixed response from my testing out merging this branch with others. #3720 didn't get any conflicts, but #3320 had conflicts in one of the later commits, no idea why. So might not be a big problem with the conflicts.

Is there any way to enforce that only LF line endings are committed after this? Maybe through .gitattributes file - https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings ?

**Comment by jonyMarino** [comment]
Good idea! I think this configuration will accomplish that: 

> text eol=lf Git will always convert line endings to LF on checkout. You should use this for files that must keep LF endings, even on Windows.

We can wait to merge this until we get no conflicts from the current open PRs

**Comment by jonyMarino** [comment]
Let's close this for safety

**Pull request closed without merging**
