### PR TITLE
Update json.hpp to latest version

### PR DESCRIPTION
**Pull request by jmackay2**
This removes various compiler warnings as well as various other improvements.

### CODE REVIEW

**Comment by jonyMarino** [comment]
Hi @jmackay2, thanks for contributing! This is a copy-paste from nlohmann repository? Can you provide a link to the original file? That will help us for reviewing this.

**Comment by jmackay2** [comment]
Yeah, this file has changed extensively over the last 4+ years since the last update, which makes it really hard to see all of the individual changes. This is just a copy-paste to pull in the latest version. 

Here is link to the original file at version 3.10.5 (latest release):
[json.hpp](https://github.com/nlohmann/json/blob/4f8fba14066156b73f1189a2b8bd568bde5284c5/single_include/nlohmann/json.hpp)

And here is the Changelog. Of interest are the updates from 2.1.1 to 3.10.5:
[Changelog](https://github.com/nlohmann/json/blob/4f8fba14066156b73f1189a2b8bd568bde5284c5/ChangeLog.md)

**Comment by zimmy87** [comment]
Hey @jmackay2, we're reviewing this PR and noticed the json.hpp file included in this PR is different from the file you linked to [here](https://github.com/nlohmann/json/blob/4f8fba14066156b73f1189a2b8bd568bde5284c5/single_include/nlohmann/json.hpp). Do you know what is the cause for the difference between these two versions of the file?

**Comment by jmackay2** [comment]
> Hey @jmackay2, we're reviewing this PR and noticed the json.hpp file included in this PR is different from the file you linked to [here](https://github.com/nlohmann/json/blob/4f8fba14066156b73f1189a2b8bd568bde5284c5/single_include/nlohmann/json.hpp). Do you know what is the cause for the difference between these two versions of the file?

I'm not sure where those differences came from, which were mostly whitespace. I went through and reconciled all of the differences so it is identical to 3.10.5.

@zimmy87 Thank you for the clang format update.

**Comment by zimmy87** [comment]
Thanks for the contribution @jmackay2! moving ahead with merge

**Pull request merged**
