### PR TITLE
added ROS client package in python

### PR DESCRIPTION
**Pull request by Mayankm96**
I have added a standalone package for ROS which interfaces with the AirSim plugin using the Python APIs. It is a followup on the issue #1326. Currently the following implementations are supported:

- client node to retrieve the drone's pose and camera images (rgb, depth)
- client node that  subscribes to an array of waypoints message and  follows a trajectory
- urdf file for the drone to publish static transformations

The package can also be found out [here](https://github.com/Mayankm96/airsim_ros_client). I hope to add more implementations depending on the suggestions and ideas I receive, but this is all that I have done so far.

### CODE REVIEW

**Comment by sytelus** [comment]
Hi @Mayankm96 - thanks for your contribution! We see few issues and wondering if we can clean this up.

1. Can we remove your private copy of PythonClient? If you are looking to set path to existing PythonClient then look for setup_path.py which does this.

2. There are bunch of DJI meshes and binary files. Are these under MIT license? If you had downloaded from commercial websites, could you please let us know what is redistribution policy?

**Comment by Mayankm96** [comment]
Hey @sytelus,  

I have deleted the PythonClient folder. The DJI M100 mesh was downloaded from [here](https://grabcad.com/library/m100-2). Under the terms of GrabCAD ([link](https://grabcad.com/terms)), I suppose the model can be used only for non-commercial use with proper credits to the originial contributor.

**Comment by Mayankm96** [comment]
Sorry I checked the GrabCAD page again. The STEP file used there was downloaded from DJI website. The link to the same is https://www.dji.com/matrice100/info#downloads.

**Comment by sytelus** [comment]
Thanks Mayank! Just one more thing... we already have few ROS publisher nodes contributed by someone else here:
https://github.com/Microsoft/AirSim/tree/master/PythonClient/ros

Do you think we can merge this existing ROS code with your PR so we have only one official story for ROS.

**Comment by TritonSailor** [comment]
Hi, great to see more ROS support.  Please don't make any breaking changes to the existing ROS code.  I have a project underway with PR in, to add Nvidia neural network navigation support for AirSim that relies on this code.


https://www.youtube.com/watch?v=9a-wvXwpRZk

https://github.com/NVIDIA-AI-IOT/redtail/pull/93

Documentation in progress here:  https://github.com/TritonSailor/redtail/wiki/Getting-Started-with-Autonomous-Navigation-Training-and-Testing-using-airsim_ros-package

**Comment by Mayankm96** [comment]
@sytelus Yeah sure, I can do that. I also think the code I have written can be improved a lot. Tt would be better to have the functionalities in form of python classes which can be imported into a python node and used.[ I was looking into [carla_ros_bridge](https://github.com/carla-simulator/carla/tree/master/carla_ros_bridge) for inspiration.

@TritonSailor I suppose my PR would take a while to get accepted. There is still a lot that I feel needs to be done to have the kind of ROS support a user would like for AirSim. Don't worry :)

**Comment by sytelus** [comment]
Hi @Mayankm96 - thanks for taking this initiative! Looking forward to your next update!!

**Comment by madratman** [comment]
closing as a generic version was added in https://github.com/microsoft/AirSim/pull/1911

**Comment by madratman** [comment]
@Mayankm96 this was a pretty good contribution, but unfortunately I didn't merge this as it would have required the user to keep writing callbacks manually with different vehicles/sensors/cameras.

**Pull request closed without merging**
