### PR TITLE
Added 'Pilot' view to AirSim

### PR DESCRIPTION
**Pull request by Timebutt**
I have written and tested code to add the 'Pilot' view functionality to AirSim, following thoughts and discussion in issue #254.

### CODE REVIEW

**Comment by sytelus** [comment]
Sorry about the delay in reply. 
I'm still trying to understand "pilot view". Traditionally FPV view is the pilot view (i.e. as if you are sitting in the drone). The ground view is supposed to be about 6 feet from ground level. It simulated view of a person who is running after drone on the ground. Currently we don't do ground detection using ray trace (which is now super easy via function in AirBluePrintLib) so z is kind of fixed. But that's easy to fix.

Some comments on PR iteself:
- it would be good to squash the commits so its easy to review changes
- looks like changes in AirBlueprintLib.cpp and .h is mostly white spaces? It's hard to see changes in these files.
- Could you describe changes in binary file .uasset? I'd moved most of the BP code to C++ so there should be no need to change .uasset anymore.
- Probably not a good idea to change kbd assignments.
- Probably not a good idea to define macros like print(text)

**Comment by Timebutt** [comment]
Hi @sytelus, thank you for your reply.

I will try to explain the issues I am having with the current views in AirSim and the reason why I added _Pilot view_ (I get that the name can be confusing but I didn't find anything better so far - a UAV _pilot_ to me, is the stationary person actually flying the drone). The current _Ground View_ has two problems for me:

1. The observer is always 6ft above 'ground level', which poses a problem in _Mountain Landscape_ as my takeoff point generally is a lot higher (see my comment visually explaining this [here]( https://github.com/Microsoft/AirSim/issues/254#issuecomment-306438359)). As the image shows, this far away from the drone it's almost impossible to fly still see it.
Granted: it seems adding ground detection using ray trace may fix this issue, and always place the observer 6ft above the actual terrain.

2. I use AirSim not only for my research, but also as a simulator to fly a drone and learn difficult maneuvers (figure 8, flying a POI around an object, ...). The _Ground View_ is not a realistic way of looking at the drone as the 'drone pilot': no pilot is running around at the same speed of the drone, always positioned perfectly beneath it. In reality, a UAV pilot chooses a comfortable and safe spot to fly and stays there for most of the flight. This is exactly the situation I have recreated here. 
No current view allows me to correctly evaluate the flight path I am doing as they are always fix, relative to the drone. Figure 8 for instance, I can't assess if my two circles were equal in size and if they touched nicely when the camera is always following the drone. An important exercise for the UAV pilot licence here that I am currently training in AirSim.

3. The _Ground View_ does not allow the user to position the observer, relative to the drone. My view does: if you move the camera director around, you basically position the UAV pilot. You could recreate a situation where the pilot is up the hill, a little further away from the drone looking down on things, or up close right next to the drone. _Ground View_ has no such flexibility.

Maybe properly naming the view could make things a lot clearer, but I'm not sure what would be more appropriate. Have I explained to some extent, what I envision and created this view for?

If it's not the AirSim intention to include a 'flight simulator' element, I understand and will withdraw the pull request. I just needed this function for myself, and thought maybe other could benefit from it too.

As for your PR comments, you are absolutely right. I think I crammed in too much stuff last-minute and didn't do a proper job of presenting it in a clean way. This is my first time committing to a project of this size. I will edit my pull request so that you can see clearly what the exact changes are, and add a screenshot of the changed binary file.

**Comment by sytelus** [comment]
Sorry about delay in response. I'm still struggling to understand what you mean by "Pilot View". Do you mean, its same as ground observer mode but camera stays at same place (only orientation changes?).

**Comment by szx0112** [comment]
This is exactly I am looking for. I view from the remote pilot while the drone is flying. I just wondering if this function has been added in the AirSim.

**Pull request closed without merging**
